### PR TITLE
Create tables / Migrations (issue #64)

### PR DESCRIPTION
**Pull request by UnknownJoe796**
This is a work-in-progress PR for supporting migrations in Ktorm. (issue #64)

I figured I'd put this up earlier rather than later so that you could review it and set me on your desired path for the implementation, rather than submitting something complete that didn't suit the project.

I have attempted to follow the standards already set by defining these operations as SqlExpressions. However, I thought it might be best to integrate constraints directly within BaseTable.

The general plan is this:

- Migrations are Kotlin files in your project that run the needed modifications to the database, and optionally can do more.
- These migrations are auto-generated by running a function, which the user will likely want to do from their main() function when certain args are passed in. Alternatively, one could use a different main entrypoint.
- There is an automatically updated AllMigrations.kt file that references the latest migration files
- Migration files reference their previous migrations, creating a full dependency chain
- Migration status (which migrations have been run) is stored inside of a special table inside of the database

Known items needed:

- Doc comments on everything
- More tests
- Actually making and running the migrations
- Support for each individual dialect
- Size of VARCHAR stored in the column

### CODE REVIEW

**Comment by UnknownJoe796** [comment]
After some more consideration, I took to moving the migration related code into its own submodule.
The one problem is that concrete DB implementations will need to depend on this module if they are to support migrations.

**Comment by vincentlauvlwj** [comment]
Thank you for your awesome PR!!! This is what I have always wanted to do. AWESOME THANKS!!!

> These migrations are auto-generated by running a function, which the user will likely want to do from their main() function when certain args are passed in. Alternatively, one could use a different main entrypoint.

In my opinion, it's better to generate those migration files by running a gradle/maven plugin, which is a more general practice than writing a different main() function. A gradle/maven plugin can provide not only a user-friendly command to generate migrations (eg. `mvn ktorm:migrate`, `gradle ktormMigrate`) but also a better place to configure the arguments that are need to for migrations (like database address etc.). The argument configurations should be in build scripts, not in project files. 

> After some more consideration, I took to moving the migration related code into its own submodule.

Actually, I think it should be moved to an independent repo, not just a submodule, because I'm planning to provide plugins for  gradle and maven, there will be many modules in the new repo, right?

**Comment by vincentlauvlwj** [comment]
Thank you for your awesome PR!!! This is what I have always wanted to do. AWESOME THANKS!!!

> These migrations are auto-generated by running a function, which the user will likely want to do from their main() function when certain args are passed in. Alternatively, one could use a different main entrypoint.

In my opinion, it's better to generate those migration files by running a gradle/maven plugin, which is a more general practice than writing a different main() function. A gradle/maven plugin can provide not only a user-friendly command to generate migrations (eg. `mvn ktorm:migrate`, `gradle ktormMigrate`) but also a better place to configure the arguments that are need to for migrations (like database address etc.). The argument configurations should be in build scripts, not in project files. 

> After some more consideration, I took to moving the migration related code into its own submodule.

Actually, I think it should be moved to an independent repo, not just a submodule, because I'm planning to provide plugins for  gradle and maven, there will be many modules in the new repo, right?

**Comment by vincentlauvlwj** [comment]
I've send a invitation to you, please accept it then I'll give you the permission to directly make commits to the new repo https://github.com/kotlin-orm/ktorm-migration

**Comment by UnknownJoe796** [comment]
Fantastic!  Thank you!

I'm having troubles with attaching any metadata to a column due to the current setup of column registration - because columns are immutable AND are registered privately inside of `BaseTable`, I can't keep any metadata on it easily.

I'll be making a PR that will add metadata to columns.  I'm going to see to it that columns remain immutable and there's no major breaking change to usage.

**Comment by UnknownJoe796** [comment]
@vincentlauvlwj How would you like to communicate for reviewing the contents and planning of `ktorm-migration`?

**Comment by vincentlauvlwj** [comment]
I don't have much time on weekdays, so let me review your code this weekend. If you have any thoughts or questions, you can  open discussions here https://github.com/kotlin-orm/ktorm-migration/discussions

**Pull request closed without merging**
